[package]
name        = "jmap"
version     = "0.0.2"
description = "JMAP parser/generator"
license     = "MIT"
authors     = [ "Robert Norris <robn@robn.io>" ]
repository  = "https://github.com/robn/jmap-rs"

[lib]
name = "jmap"

[dependencies]
rustc-serialize = "*"
uuid = "*"
