[package]
name        = "jmap"
description = "JMAP"
repository  = "https://github.com/robn/jmap-rs"
version     = "0.0.1"
license     = "MIT"
authors     = [ "Robert Norris <robn@robn.io>" ]

[[bin]]
name = "jmap"

[dependencies]
rustc-serialize = "0.3.12"
