[package]
name        = "jmap"
version     = "0.0.5"
description = "JMAP parser/generator"
license     = "MIT"
authors     = [ "Robert Norris <robn@robn.io>" ]
repository  = "https://github.com/robn/jmap-rs"

[lib]
name = "jmap"

[dependencies]
rustc-serialize = "0.*"
uuid = "0.*"
chrono = "0.*"
